<%@page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
	<%@include file="/WEB-INF/jsp/common/taglib.jsp"%>
				<td>
									${tempBean.name}
				</td>
				<td>
									${tempBean.brand}
				</td>
				<td>
									${tempBean.category.name}
				</td>
				<td>
									${tempBean.picture.manageKey}
				</td>
				<td>
									${tempBean.description}
				</td>
				<td>
									${tempBean.spec}
				</td>
				<td>
									${tempBean.qrCode.manageKey}
				</td>
				<td>
									${tempBean.productAddr}
				</td>
				<td>
									${tempBean.trace}
				</td>
				<td>
								<fmt:formatDate value="${tempBean.deadline}" pattern="${applicationScope.EN_YEAR_MONTH_DAY_HOUR_MIN_SEC}"/>
				</td>
				<td>
									${tempBean.batchNum}
				</td>
				<td>
									${tempBean.standard}
				</td>
				<td>
									${tempBean.tel}
				</td>
				<td>
									${productStatusMap[tempBean.status]}
				</td>
				<td>
									${tempBean.creator.manageKey}
				</td>